//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace GrupoA.Sincronizacao.ServicoPortal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AM_PORTALSOAP", Namespace="http://10.1.1.25:8182/ws/")]
    public partial class AM_PORTAL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GETCLIENTESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETFORNECEDORESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETNOTASFISCAISOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETPEDIDOVENDAOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETPRENFEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETPROSPECTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETSTATUSPEDNFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AM_PORTAL() {
            this.Url = global::GrupoA.Sincronizacao.Properties.Settings.Default.GrupoA_Sincronizacao_ServicoPortal_AM_PORTAL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GETCLIENTESCompletedEventHandler GETCLIENTESCompleted;
        
        /// <remarks/>
        public event GETFORNECEDORESCompletedEventHandler GETFORNECEDORESCompleted;
        
        /// <remarks/>
        public event GETNOTASFISCAISCompletedEventHandler GETNOTASFISCAISCompleted;
        
        /// <remarks/>
        public event GETPEDIDOVENDACompletedEventHandler GETPEDIDOVENDACompleted;
        
        /// <remarks/>
        public event GETPRENFECompletedEventHandler GETPRENFECompleted;
        
        /// <remarks/>
        public event GETPROSPECTCompletedEventHandler GETPROSPECTCompleted;
        
        /// <remarks/>
        public event GETSTATUSPEDNFCompletedEventHandler GETSTATUSPEDNFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETCLIENTES", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETCLIENTESRESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETCLIENTESRESULT")]
        public string GETCLIENTES(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WA1_CGC, 
                    string WA1_TIPO, 
                    string WA1_PESSOA, 
                    string WA1_NOME, 
                    string WA1_NREDUZ, 
                    string WA1_INSCR, 
                    string WA1_INSCRM, 
                    string WA1_END, 
                    string WA1_BAIRRO, 
                    string WA1_COD_MUN, 
                    string WA1_MUN, 
                    string WA1_EST, 
                    string WA1_CEP, 
                    string WA1_EMAIL, 
                    string WA1_DDD, 
                    string WA1_TEL, 
                    string WA1_HPAGE) {
            object[] results = this.Invoke("GETCLIENTES", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WA1_CGC,
                        WA1_TIPO,
                        WA1_PESSOA,
                        WA1_NOME,
                        WA1_NREDUZ,
                        WA1_INSCR,
                        WA1_INSCRM,
                        WA1_END,
                        WA1_BAIRRO,
                        WA1_COD_MUN,
                        WA1_MUN,
                        WA1_EST,
                        WA1_CEP,
                        WA1_EMAIL,
                        WA1_DDD,
                        WA1_TEL,
                        WA1_HPAGE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETCLIENTESAsync(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WA1_CGC, 
                    string WA1_TIPO, 
                    string WA1_PESSOA, 
                    string WA1_NOME, 
                    string WA1_NREDUZ, 
                    string WA1_INSCR, 
                    string WA1_INSCRM, 
                    string WA1_END, 
                    string WA1_BAIRRO, 
                    string WA1_COD_MUN, 
                    string WA1_MUN, 
                    string WA1_EST, 
                    string WA1_CEP, 
                    string WA1_EMAIL, 
                    string WA1_DDD, 
                    string WA1_TEL, 
                    string WA1_HPAGE) {
            this.GETCLIENTESAsync(WSEMPRESA, WSFILIAL, WSLOGIN, WSSENHA, WA1_CGC, WA1_TIPO, WA1_PESSOA, WA1_NOME, WA1_NREDUZ, WA1_INSCR, WA1_INSCRM, WA1_END, WA1_BAIRRO, WA1_COD_MUN, WA1_MUN, WA1_EST, WA1_CEP, WA1_EMAIL, WA1_DDD, WA1_TEL, WA1_HPAGE, null);
        }
        
        /// <remarks/>
        public void GETCLIENTESAsync(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WA1_CGC, 
                    string WA1_TIPO, 
                    string WA1_PESSOA, 
                    string WA1_NOME, 
                    string WA1_NREDUZ, 
                    string WA1_INSCR, 
                    string WA1_INSCRM, 
                    string WA1_END, 
                    string WA1_BAIRRO, 
                    string WA1_COD_MUN, 
                    string WA1_MUN, 
                    string WA1_EST, 
                    string WA1_CEP, 
                    string WA1_EMAIL, 
                    string WA1_DDD, 
                    string WA1_TEL, 
                    string WA1_HPAGE, 
                    object userState) {
            if ((this.GETCLIENTESOperationCompleted == null)) {
                this.GETCLIENTESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETCLIENTESOperationCompleted);
            }
            this.InvokeAsync("GETCLIENTES", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WA1_CGC,
                        WA1_TIPO,
                        WA1_PESSOA,
                        WA1_NOME,
                        WA1_NREDUZ,
                        WA1_INSCR,
                        WA1_INSCRM,
                        WA1_END,
                        WA1_BAIRRO,
                        WA1_COD_MUN,
                        WA1_MUN,
                        WA1_EST,
                        WA1_CEP,
                        WA1_EMAIL,
                        WA1_DDD,
                        WA1_TEL,
                        WA1_HPAGE}, this.GETCLIENTESOperationCompleted, userState);
        }
        
        private void OnGETCLIENTESOperationCompleted(object arg) {
            if ((this.GETCLIENTESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETCLIENTESCompleted(this, new GETCLIENTESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETFORNECEDORES", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETFORNECEDORESRESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETFORNECEDORESRESULT")]
        public string GETFORNECEDORES(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WA2_CGC, 
                    string WA2_TIPO, 
                    string WA2_NOME, 
                    string WA2_NREDUZ, 
                    string WA2_INSCR, 
                    string WA2_INSCRM, 
                    string WA2_END, 
                    string WA2_BAIRRO, 
                    string WA2_COD_MUN, 
                    string WA2_MUN, 
                    string WA2_EST, 
                    string WA2_CEP, 
                    string WA2_EMAIL, 
                    string WA2_DDD, 
                    string WA2_TEL, 
                    string WA2_HPAGE, 
                    string WA2_CONTATO) {
            object[] results = this.Invoke("GETFORNECEDORES", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WA2_CGC,
                        WA2_TIPO,
                        WA2_NOME,
                        WA2_NREDUZ,
                        WA2_INSCR,
                        WA2_INSCRM,
                        WA2_END,
                        WA2_BAIRRO,
                        WA2_COD_MUN,
                        WA2_MUN,
                        WA2_EST,
                        WA2_CEP,
                        WA2_EMAIL,
                        WA2_DDD,
                        WA2_TEL,
                        WA2_HPAGE,
                        WA2_CONTATO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETFORNECEDORESAsync(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WA2_CGC, 
                    string WA2_TIPO, 
                    string WA2_NOME, 
                    string WA2_NREDUZ, 
                    string WA2_INSCR, 
                    string WA2_INSCRM, 
                    string WA2_END, 
                    string WA2_BAIRRO, 
                    string WA2_COD_MUN, 
                    string WA2_MUN, 
                    string WA2_EST, 
                    string WA2_CEP, 
                    string WA2_EMAIL, 
                    string WA2_DDD, 
                    string WA2_TEL, 
                    string WA2_HPAGE, 
                    string WA2_CONTATO) {
            this.GETFORNECEDORESAsync(WSEMPRESA, WSFILIAL, WSLOGIN, WSSENHA, WA2_CGC, WA2_TIPO, WA2_NOME, WA2_NREDUZ, WA2_INSCR, WA2_INSCRM, WA2_END, WA2_BAIRRO, WA2_COD_MUN, WA2_MUN, WA2_EST, WA2_CEP, WA2_EMAIL, WA2_DDD, WA2_TEL, WA2_HPAGE, WA2_CONTATO, null);
        }
        
        /// <remarks/>
        public void GETFORNECEDORESAsync(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WA2_CGC, 
                    string WA2_TIPO, 
                    string WA2_NOME, 
                    string WA2_NREDUZ, 
                    string WA2_INSCR, 
                    string WA2_INSCRM, 
                    string WA2_END, 
                    string WA2_BAIRRO, 
                    string WA2_COD_MUN, 
                    string WA2_MUN, 
                    string WA2_EST, 
                    string WA2_CEP, 
                    string WA2_EMAIL, 
                    string WA2_DDD, 
                    string WA2_TEL, 
                    string WA2_HPAGE, 
                    string WA2_CONTATO, 
                    object userState) {
            if ((this.GETFORNECEDORESOperationCompleted == null)) {
                this.GETFORNECEDORESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETFORNECEDORESOperationCompleted);
            }
            this.InvokeAsync("GETFORNECEDORES", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WA2_CGC,
                        WA2_TIPO,
                        WA2_NOME,
                        WA2_NREDUZ,
                        WA2_INSCR,
                        WA2_INSCRM,
                        WA2_END,
                        WA2_BAIRRO,
                        WA2_COD_MUN,
                        WA2_MUN,
                        WA2_EST,
                        WA2_CEP,
                        WA2_EMAIL,
                        WA2_DDD,
                        WA2_TEL,
                        WA2_HPAGE,
                        WA2_CONTATO}, this.GETFORNECEDORESOperationCompleted, userState);
        }
        
        private void OnGETFORNECEDORESOperationCompleted(object arg) {
            if ((this.GETFORNECEDORESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETFORNECEDORESCompleted(this, new GETFORNECEDORESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETNOTASFISCAIS", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETNOTASFISCAISRESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GETNOTASFISCAISRESULT")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NFISCAISVIEW[] GETNOTASFISCAIS(string WSEMPRESA, string WSFILIAL, string WSCPF) {
            object[] results = this.Invoke("GETNOTASFISCAIS", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSCPF});
            return ((NFISCAISVIEW[])(results[0]));
        }
        
        /// <remarks/>
        public void GETNOTASFISCAISAsync(string WSEMPRESA, string WSFILIAL, string WSCPF) {
            this.GETNOTASFISCAISAsync(WSEMPRESA, WSFILIAL, WSCPF, null);
        }
        
        /// <remarks/>
        public void GETNOTASFISCAISAsync(string WSEMPRESA, string WSFILIAL, string WSCPF, object userState) {
            if ((this.GETNOTASFISCAISOperationCompleted == null)) {
                this.GETNOTASFISCAISOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETNOTASFISCAISOperationCompleted);
            }
            this.InvokeAsync("GETNOTASFISCAIS", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSCPF}, this.GETNOTASFISCAISOperationCompleted, userState);
        }
        
        private void OnGETNOTASFISCAISOperationCompleted(object arg) {
            if ((this.GETNOTASFISCAISCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETNOTASFISCAISCompleted(this, new GETNOTASFISCAISCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETPEDIDOVENDA", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETPEDIDOVENDARESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETPEDIDOVENDARESULT")]
        public string GETPEDIDOVENDA(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WC5_CLI_CNPJ, string WC5_CONDPAG, string WC5_TPFRETE, float WC5_FRETE, float WC5_DESC1, float WC5_DESCONT, ITEMPEDVENDA ITEMPVENDA) {
            object[] results = this.Invoke("GETPEDIDOVENDA", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WC5_CLI_CNPJ,
                        WC5_CONDPAG,
                        WC5_TPFRETE,
                        WC5_FRETE,
                        WC5_DESC1,
                        WC5_DESCONT,
                        ITEMPVENDA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETPEDIDOVENDAAsync(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WC5_CLI_CNPJ, string WC5_CONDPAG, string WC5_TPFRETE, float WC5_FRETE, float WC5_DESC1, float WC5_DESCONT, ITEMPEDVENDA ITEMPVENDA) {
            this.GETPEDIDOVENDAAsync(WSEMPRESA, WSFILIAL, WSLOGIN, WSSENHA, WC5_CLI_CNPJ, WC5_CONDPAG, WC5_TPFRETE, WC5_FRETE, WC5_DESC1, WC5_DESCONT, ITEMPVENDA, null);
        }
        
        /// <remarks/>
        public void GETPEDIDOVENDAAsync(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WC5_CLI_CNPJ, string WC5_CONDPAG, string WC5_TPFRETE, float WC5_FRETE, float WC5_DESC1, float WC5_DESCONT, ITEMPEDVENDA ITEMPVENDA, object userState) {
            if ((this.GETPEDIDOVENDAOperationCompleted == null)) {
                this.GETPEDIDOVENDAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETPEDIDOVENDAOperationCompleted);
            }
            this.InvokeAsync("GETPEDIDOVENDA", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WC5_CLI_CNPJ,
                        WC5_CONDPAG,
                        WC5_TPFRETE,
                        WC5_FRETE,
                        WC5_DESC1,
                        WC5_DESCONT,
                        ITEMPVENDA}, this.GETPEDIDOVENDAOperationCompleted, userState);
        }
        
        private void OnGETPEDIDOVENDAOperationCompleted(object arg) {
            if ((this.GETPEDIDOVENDACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETPEDIDOVENDACompleted(this, new GETPEDIDOVENDACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETPRENFE", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETPRENFERESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETPRENFERESULT")]
        public string GETPRENFE(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WF1_FOR_CNPJ, string WF1_DOC, string WF1_SERIE, string WF1_TIPO, string WF1_EST, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime WF1_EMISSAO, string WF1_ESPECIE, string WF1_OBSNFE, ITEMPRENFE ITEMP_NFE) {
            object[] results = this.Invoke("GETPRENFE", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WF1_FOR_CNPJ,
                        WF1_DOC,
                        WF1_SERIE,
                        WF1_TIPO,
                        WF1_EST,
                        WF1_EMISSAO,
                        WF1_ESPECIE,
                        WF1_OBSNFE,
                        ITEMP_NFE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETPRENFEAsync(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WF1_FOR_CNPJ, string WF1_DOC, string WF1_SERIE, string WF1_TIPO, string WF1_EST, System.DateTime WF1_EMISSAO, string WF1_ESPECIE, string WF1_OBSNFE, ITEMPRENFE ITEMP_NFE) {
            this.GETPRENFEAsync(WSEMPRESA, WSFILIAL, WSLOGIN, WSSENHA, WF1_FOR_CNPJ, WF1_DOC, WF1_SERIE, WF1_TIPO, WF1_EST, WF1_EMISSAO, WF1_ESPECIE, WF1_OBSNFE, ITEMP_NFE, null);
        }
        
        /// <remarks/>
        public void GETPRENFEAsync(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WF1_FOR_CNPJ, string WF1_DOC, string WF1_SERIE, string WF1_TIPO, string WF1_EST, System.DateTime WF1_EMISSAO, string WF1_ESPECIE, string WF1_OBSNFE, ITEMPRENFE ITEMP_NFE, object userState) {
            if ((this.GETPRENFEOperationCompleted == null)) {
                this.GETPRENFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETPRENFEOperationCompleted);
            }
            this.InvokeAsync("GETPRENFE", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WF1_FOR_CNPJ,
                        WF1_DOC,
                        WF1_SERIE,
                        WF1_TIPO,
                        WF1_EST,
                        WF1_EMISSAO,
                        WF1_ESPECIE,
                        WF1_OBSNFE,
                        ITEMP_NFE}, this.GETPRENFEOperationCompleted, userState);
        }
        
        private void OnGETPRENFEOperationCompleted(object arg) {
            if ((this.GETPRENFECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETPRENFECompleted(this, new GETPRENFECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETPROSPECT", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETPROSPECTRESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETPROSPECTRESULT")]
        public string GETPROSPECT(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WUS_CGC, 
                    string WUS_NOME, 
                    string WUS_NREDUZ, 
                    string WUS_PESSOA, 
                    string WUS_END, 
                    string WUS_BAIRRO, 
                    string WUS_MUN, 
                    string WUS_EST, 
                    string WUS_CEP, 
                    string WUS_EMAIL, 
                    string WUS_DDD, 
                    string WUS_TEL, 
                    string WUS_URL, 
                    string WUS_COD_MUN, 
                    string WUS_PAIS) {
            object[] results = this.Invoke("GETPROSPECT", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WUS_CGC,
                        WUS_NOME,
                        WUS_NREDUZ,
                        WUS_PESSOA,
                        WUS_END,
                        WUS_BAIRRO,
                        WUS_MUN,
                        WUS_EST,
                        WUS_CEP,
                        WUS_EMAIL,
                        WUS_DDD,
                        WUS_TEL,
                        WUS_URL,
                        WUS_COD_MUN,
                        WUS_PAIS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETPROSPECTAsync(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WUS_CGC, 
                    string WUS_NOME, 
                    string WUS_NREDUZ, 
                    string WUS_PESSOA, 
                    string WUS_END, 
                    string WUS_BAIRRO, 
                    string WUS_MUN, 
                    string WUS_EST, 
                    string WUS_CEP, 
                    string WUS_EMAIL, 
                    string WUS_DDD, 
                    string WUS_TEL, 
                    string WUS_URL, 
                    string WUS_COD_MUN, 
                    string WUS_PAIS) {
            this.GETPROSPECTAsync(WSEMPRESA, WSFILIAL, WSLOGIN, WSSENHA, WUS_CGC, WUS_NOME, WUS_NREDUZ, WUS_PESSOA, WUS_END, WUS_BAIRRO, WUS_MUN, WUS_EST, WUS_CEP, WUS_EMAIL, WUS_DDD, WUS_TEL, WUS_URL, WUS_COD_MUN, WUS_PAIS, null);
        }
        
        /// <remarks/>
        public void GETPROSPECTAsync(
                    string WSEMPRESA, 
                    string WSFILIAL, 
                    string WSLOGIN, 
                    string WSSENHA, 
                    string WUS_CGC, 
                    string WUS_NOME, 
                    string WUS_NREDUZ, 
                    string WUS_PESSOA, 
                    string WUS_END, 
                    string WUS_BAIRRO, 
                    string WUS_MUN, 
                    string WUS_EST, 
                    string WUS_CEP, 
                    string WUS_EMAIL, 
                    string WUS_DDD, 
                    string WUS_TEL, 
                    string WUS_URL, 
                    string WUS_COD_MUN, 
                    string WUS_PAIS, 
                    object userState) {
            if ((this.GETPROSPECTOperationCompleted == null)) {
                this.GETPROSPECTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETPROSPECTOperationCompleted);
            }
            this.InvokeAsync("GETPROSPECT", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WUS_CGC,
                        WUS_NOME,
                        WUS_NREDUZ,
                        WUS_PESSOA,
                        WUS_END,
                        WUS_BAIRRO,
                        WUS_MUN,
                        WUS_EST,
                        WUS_CEP,
                        WUS_EMAIL,
                        WUS_DDD,
                        WUS_TEL,
                        WUS_URL,
                        WUS_COD_MUN,
                        WUS_PAIS}, this.GETPROSPECTOperationCompleted, userState);
        }
        
        private void OnGETPROSPECTOperationCompleted(object arg) {
            if ((this.GETPROSPECTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETPROSPECTCompleted(this, new GETPROSPECTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.25:8182/ws/GETSTATUSPEDNF", RequestNamespace="http://10.1.1.25:8182/ws/", ResponseElementName="GETSTATUSPEDNFRESPONSE", ResponseNamespace="http://10.1.1.25:8182/ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETSTATUSPEDNFRESULT")]
        public bool GETSTATUSPEDNF(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WSNOTAFISCAL, string WSSERIENOTAFISCAL) {
            object[] results = this.Invoke("GETSTATUSPEDNF", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WSNOTAFISCAL,
                        WSSERIENOTAFISCAL});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GETSTATUSPEDNFAsync(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WSNOTAFISCAL, string WSSERIENOTAFISCAL) {
            this.GETSTATUSPEDNFAsync(WSEMPRESA, WSFILIAL, WSLOGIN, WSSENHA, WSNOTAFISCAL, WSSERIENOTAFISCAL, null);
        }
        
        /// <remarks/>
        public void GETSTATUSPEDNFAsync(string WSEMPRESA, string WSFILIAL, string WSLOGIN, string WSSENHA, string WSNOTAFISCAL, string WSSERIENOTAFISCAL, object userState) {
            if ((this.GETSTATUSPEDNFOperationCompleted == null)) {
                this.GETSTATUSPEDNFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETSTATUSPEDNFOperationCompleted);
            }
            this.InvokeAsync("GETSTATUSPEDNF", new object[] {
                        WSEMPRESA,
                        WSFILIAL,
                        WSLOGIN,
                        WSSENHA,
                        WSNOTAFISCAL,
                        WSSERIENOTAFISCAL}, this.GETSTATUSPEDNFOperationCompleted, userState);
        }
        
        private void OnGETSTATUSPEDNFOperationCompleted(object arg) {
            if ((this.GETSTATUSPEDNFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETSTATUSPEDNFCompleted(this, new GETSTATUSPEDNFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.1.1.25:8182/ws/")]
    public partial class NFISCAISVIEW {
        
        private string nF_DATAEMISSAOField;
        
        private string nF_DATAENTREGAITEMPV01Field;
        
        private string nF_DESCRICAOITEMPV01Field;
        
        private string nF_ITEMPV01Field;
        
        private string nF_NUMEROField;
        
        private string nF_PRODUTOITEMPV01Field;
        
        /// <remarks/>
        public string NF_DATAEMISSAO {
            get {
                return this.nF_DATAEMISSAOField;
            }
            set {
                this.nF_DATAEMISSAOField = value;
            }
        }
        
        /// <remarks/>
        public string NF_DATAENTREGAITEMPV01 {
            get {
                return this.nF_DATAENTREGAITEMPV01Field;
            }
            set {
                this.nF_DATAENTREGAITEMPV01Field = value;
            }
        }
        
        /// <remarks/>
        public string NF_DESCRICAOITEMPV01 {
            get {
                return this.nF_DESCRICAOITEMPV01Field;
            }
            set {
                this.nF_DESCRICAOITEMPV01Field = value;
            }
        }
        
        /// <remarks/>
        public string NF_ITEMPV01 {
            get {
                return this.nF_ITEMPV01Field;
            }
            set {
                this.nF_ITEMPV01Field = value;
            }
        }
        
        /// <remarks/>
        public string NF_NUMERO {
            get {
                return this.nF_NUMEROField;
            }
            set {
                this.nF_NUMEROField = value;
            }
        }
        
        /// <remarks/>
        public string NF_PRODUTOITEMPV01 {
            get {
                return this.nF_PRODUTOITEMPV01Field;
            }
            set {
                this.nF_PRODUTOITEMPV01Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.1.1.25:8182/ws/")]
    public partial class PRENFEESTRU {
        
        private string wD1_CCField;
        
        private string wD1_CODField;
        
        private string wD1_CONTAField;
        
        private float wD1_QUANTField;
        
        private float wD1_VUNITField;
        
        /// <remarks/>
        public string WD1_CC {
            get {
                return this.wD1_CCField;
            }
            set {
                this.wD1_CCField = value;
            }
        }
        
        /// <remarks/>
        public string WD1_COD {
            get {
                return this.wD1_CODField;
            }
            set {
                this.wD1_CODField = value;
            }
        }
        
        /// <remarks/>
        public string WD1_CONTA {
            get {
                return this.wD1_CONTAField;
            }
            set {
                this.wD1_CONTAField = value;
            }
        }
        
        /// <remarks/>
        public float WD1_QUANT {
            get {
                return this.wD1_QUANTField;
            }
            set {
                this.wD1_QUANTField = value;
            }
        }
        
        /// <remarks/>
        public float WD1_VUNIT {
            get {
                return this.wD1_VUNITField;
            }
            set {
                this.wD1_VUNITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.1.1.25:8182/ws/")]
    public partial class ITEMPRENFE {
        
        private PRENFEESTRU[] iTENSP_NFEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PRENFEESTRU[] ITENSP_NFE {
            get {
                return this.iTENSP_NFEField;
            }
            set {
                this.iTENSP_NFEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.1.1.25:8182/ws/")]
    public partial class ITEMPVENDAESTRU {
        
        private float wC6_DESCONTField;
        
        private System.DateTime wC6_ENTREGField;
        
        private string wC6_PEDCLIField;
        
        private float wC6_PRCVENField;
        
        private string wC6_PRODUTOField;
        
        private float wC6_QTDVENField;
        
        private float wC6_VALDESCField;
        
        /// <remarks/>
        public float WC6_DESCONT {
            get {
                return this.wC6_DESCONTField;
            }
            set {
                this.wC6_DESCONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime WC6_ENTREG {
            get {
                return this.wC6_ENTREGField;
            }
            set {
                this.wC6_ENTREGField = value;
            }
        }
        
        /// <remarks/>
        public string WC6_PEDCLI {
            get {
                return this.wC6_PEDCLIField;
            }
            set {
                this.wC6_PEDCLIField = value;
            }
        }
        
        /// <remarks/>
        public float WC6_PRCVEN {
            get {
                return this.wC6_PRCVENField;
            }
            set {
                this.wC6_PRCVENField = value;
            }
        }
        
        /// <remarks/>
        public string WC6_PRODUTO {
            get {
                return this.wC6_PRODUTOField;
            }
            set {
                this.wC6_PRODUTOField = value;
            }
        }
        
        /// <remarks/>
        public float WC6_QTDVEN {
            get {
                return this.wC6_QTDVENField;
            }
            set {
                this.wC6_QTDVENField = value;
            }
        }
        
        /// <remarks/>
        public float WC6_VALDESC {
            get {
                return this.wC6_VALDESCField;
            }
            set {
                this.wC6_VALDESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.1.1.25:8182/ws/")]
    public partial class ITEMPEDVENDA {
        
        private ITEMPVENDAESTRU[] iTENSPVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ITEMPVENDAESTRU[] ITENSPV {
            get {
                return this.iTENSPVField;
            }
            set {
                this.iTENSPVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETCLIENTESCompletedEventHandler(object sender, GETCLIENTESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETCLIENTESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETCLIENTESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETFORNECEDORESCompletedEventHandler(object sender, GETFORNECEDORESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETFORNECEDORESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETFORNECEDORESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETNOTASFISCAISCompletedEventHandler(object sender, GETNOTASFISCAISCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETNOTASFISCAISCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETNOTASFISCAISCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NFISCAISVIEW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NFISCAISVIEW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETPEDIDOVENDACompletedEventHandler(object sender, GETPEDIDOVENDACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETPEDIDOVENDACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETPEDIDOVENDACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETPRENFECompletedEventHandler(object sender, GETPRENFECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETPRENFECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETPRENFECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETPROSPECTCompletedEventHandler(object sender, GETPROSPECTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETPROSPECTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETPROSPECTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GETSTATUSPEDNFCompletedEventHandler(object sender, GETSTATUSPEDNFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETSTATUSPEDNFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETSTATUSPEDNFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591